# Generated by Django 4.1 on 2022-08-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da diária')),
                ('imagem_quarto', models.ImageField(upload_to='quarto/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name_plural': 'Tipo do quarto',
            },
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_entrada', models.DateField(verbose_name='Data de entrada')),
                ('data_saida', models.DateField(verbose_name='Data de saída')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço do produto')),
                ('tipo_quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospedagem.tipo_quarto')),
            ],
            options={
                'verbose_name_plural': 'Estadia',
            },
        ),
    ]
